config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :items do
  	resources :requests
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :items, dependent: :destroy
	validates  :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :requests, dependent: :destroy
	belongs_to :category
	validates  :title, :description, presence: true

	def self.search(search)
		Item.where("title LIKE ?  AND available LIKE ?", "%#{search}%", true).or(Item.where("description LIKE ?  AND available LIKE ?", "%#{search}%", true))
		
	end
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :item
  validates  :requester, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Categoría creada de manera exitosa.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Se actualizó la categoría de manera exitosa.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Se eliminó la categoría de manera exitosa.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :get_item, only: [:edit, :destroy, :show, :update]
	def create
		@item = Item.new(item_params)

		if @item.save
			redirect_to @item
		else
			render 'new'
		end
	end

	def destroy
		@item = Item.find(params[:id])
		@item.destoy

		redirect_to items_path
	end

	def edit
	end

	def get_item
		@item = Item.find(params[:id])
	end

	def index
		@items = Item.all
		if params[:search]
			@items = Item.search(params[:search])
		else
			@items = Item.all
		end
	end

	def new
		@item = Item.new
	end

	def show
	end

	def update
		if @item.update(item_params)
			redirect_to @item
		else
			render 'edit'
		end
	end

	private
	def item_params
		params.require(:item).permit(:title, :description)
	end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

	def create
		@item = Item.find(params[:item_id])
		@request = @item.requests.create(request_params)
		redirect_to item_path(@item)
	end

	def destroy
		@item = Item.find(params[:item_id])
		@request = @item.requests.find(params[:id])
		@request.destroy

		redirect_to item_path(@item)
	end

	private
		def request_params
			params.require(:request).permit(:requester, :body)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> No se puede guardar esta categoría:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Nombre' %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit 'Procesar' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Ver', @category %> |
<%= link_to 'Atrás', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categorías</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Ver', category %></td>
        <td><%= link_to 'Editar', edit_category_path(category) %></td>
        <td><%= link_to 'Borrar', category, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva categoría', new_category_path %>

app/views/categories/new.html.erb
<h1>Nueva categoría</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre: </strong>
  <%= @category.name %>
</p>

<%= link_to 'Editar', edit_category_path(@category) %> |
<%= link_to 'Atrás', categories_path %>

app/views/items/_form.html.erb
	<%= form_for @item do |item| %>
		<% if @item.errors.any? %>
			<div id="error_explanation">
				<h2>
					<%=  pluralize(@item.errors.count, "error") %> Imposible registrar el artículo:
				</h2>
				<ul>
					<% @item.errors.full_messages.each do |msg| %>
						<li>
							<%= msg %>
						</li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<p>
		<%= item.label :title, "Título"%> <br>
		<%= item.text_field :title %>
		</p>
		<p>
			<%= item.label :description, "Descripción"%>
			<%= item.text_area :description %>
		</p>
		<p>
			<%=item.submit "Procesar"%>
		</p>
	<% end %>

app/views/items/edit.html.erb
<h1>Editar artículo</h1>

<%= render 'form' %>

<%= link_to 'Atrás', items_path %>

app/views/items/index.html.erb
<h1>Artículos que coinciden con la búsqueda <%= params[:search] %></h1>

<% if @items.present? %>
  <% @items.each do |item| %>
  	<p>
  	<%= link_to item.title, item_path(item) %>
  	</p>
  <% end %>
<% else %>
  <p>No se consiguieron artículos <%= params[:search] %>.</p>
<% end %>

app/views/items/new.html.erb
<h1>Nuevo item</h1>
<%= render 'form' %>
<%= link_to 'Atrás', items_path %>

app/views/items/show.html.erb
<p>
	<strong>Título:</strong>
	<%= @item.title %>
</p>
<p>
	<strong>Descripción:</strong>
	<%= @item.description %>
</p>

<h2>Solicitudes</h2>
	<%= render @item.requests %>

<h2>Ingresa una petición: </h2>
	<%= render 'requests/form' %>



<%= link_to 'Editar artículo', edit_item_path %> |
<%= link_to 'Atrás', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Giveit</title>
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<style>
	.navbar {
		margin-bottom: 0;
		background-color: #0AA9BC;
		z-index: 9999;
		border: 0;
		font-size: 10px !important;
		line-height: 1.42857143 !important;
		letter-spacing: 2px;
		border-radius: 0;
	}

	.navbar li a, .navbar .navbar-brand {
		color: #fff !important;
	}

	.navbar-nav li a:hover, .navbar-nav li.active a {
		color: #f4511e !important;
		background-color: #fff !important;
	}

	.navbar-default .navbar-toggle {
		border-color: transparent;
		color: #fff !important;
	}
	</style>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="http://localhost:3000/"> <%= image_tag("small logo.png") %> </a>
			</div>
			<div class="collapse navbar-collapse" id="myNavbar">
				<ul class="nav navbar-nav navbar-right" >
					<li><a href="#about">Registrarse</a></li>
					<li><a href="#contact">Iniciar sesión</a></li>
				</ul>
			</div>
		</div>
	</nav>
</head>
<style>
.jumbotron { 
	background-color: #0AA9BC; /* Orange */
	color: #FFFFFF;
}
</style>
<body>

	<div class="jumbotron text-center">
		<h1>Giveit</h1> 
		<p>Lo que ya no necesitas, de seguro le sirve a alguien</p><br> 	
		<%= form_tag items_path, class: 'form-inline', :method => 'get' do  %>
		<%= text_field_tag :search, params[:search], class: "form-control", placeholder: 'Buscar algo', size: 50 %>	
		<%= submit_tag 'Buscar', class: 'btn btn-danger' %>
		<% end %>
	</div>
	<%= yield %>
</body>

app/views/requests/_form.html.erb
	<%= form_for([@item, @item.requests.build]) do |request|  %>
		<p>
			<%= request.label 'Su nombre' %>
			<%= request.text_field :requester %>
		</p>
		<p>
			<%= request.label 'Solicitud' %>
			<%= request.text_area :body %>
		</p>
		<p>
			<%= request.submit "Solicitar" %>
		</p>
	<% end %>

app/views/requests/_request.html.erb
<p>
	<strong>Persona: </strong>
	<%= request.requester %>
</p>
<p>
	<strong>Solicitud: </strong>
	<%= request.body %>

	<p>
		<%= link_to 'Borrar Solicitud', [request.item, request], method: :delete, data: { confirm: "¿Está seguro?"} %>
	</p>
</p>